---
#
#
# Author: John McDonough (jomcdono@cisco.com)
#         Cisco Systems, Inc.
#

- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Test that we have a UCS hostname, UCS username, and UCS password
    fail:
      msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
    when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
    vars:
      login_info: &login_info
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"

  - name: Configure DNS server
    ucs_dns_server:
      <<: *login_info
      dns_server: "{{ item.dns_server }}"
      description: "{{ item.description }}"
      state: "{{ ucs_state }}"
      delegate_to: localhost
    loop:
      "{{ DNS_SERVERS }}"
#      These variables are in group_vars/all
#      - { dns_server: '171.70.168.183', description: 'DNS Server 1 IP address' }
#      - { dns_server: '172.22.249.101', description: 'DNS Server 2 IP address' }

  - name: Add UCS Organization
    ucs_org:
      <<: *login_info
      org_name: ANSIBLE
      description: Production Servers
      state: "{{ ucs_state }}"

  - name: Add UCS Organization
    ucs_org:
      <<: *login_info
      org_name: "{{ item.name }}"
      parent_org_path: root/ANSIBLE
      description: "{{ item.description }}"
      state: "{{ ucs_state }}"
      delegate_to: localhost
    loop:
      - { name: 'LIN', description: 'Linux Servers' }
      - { name: 'WIN', description: 'Windows Servers' }
      - { name: 'ESX', description: 'VMware Servers' }

  - name: Configure VLANs
    ucs_vlans:
      <<: *login_info
      name: "{{ item.name }}-{{ item.id }}"
      id: "{{ item.id }}" 
      native: "{{ item.native }}"
      state: "{{ ucs_state }}"
    loop:
      "{{ VLANS }}"

  - name: Create Server BIOS Policy - YAML
    ucs_managed_objects:
      <<: *login_info
      objects:
      - module: ucsmsdk.mometa.bios.BiosVProfile
        class: BiosVProfile
        properties:
            parent_mo_or_dn: org-root
            name: bios-yaml
            reboot_on_update: "yes"
        children:
          - module: ucsmsdk.mometa.bios.BiosVfQuietBoot
            class: BiosVfQuietBoot
            properties:
              vp_quiet_boot: disabled
          - module: ucsmsdk.mometa.bios.BiosVfResumeOnACPowerLoss
            class: BiosVfResumeOnACPowerLoss
            properties:
              vp_resume_on_ac_power_loss: stay-off
          - module: ucsmsdk.mometa.bios.BiosVfConsoleRedirection
            class: BiosVfConsoleRedirection
            properties:
              vp_baud_rate: "9600"
              vp_console_redirection: com-0
              vp_terminal_type: pc-ansi
      state: "{{ ucs_state }}"

  - name: Create Server BIOS Policy - JSON
    ucs_managed_objects:
      <<: *login_info
      objects:
      - {
          "module": "ucsmsdk.mometa.bios.BiosVProfile",
          "class": "BiosVProfile",
          "properties": {
              "parent_mo_or_dn": "org-root",
              "name": "bios-json",
              "reboot_on_update": "yes"
              },
              "children": [
                {
                    "module": "ucsmsdk.mometa.bios.BiosVfQuietBoot",
                    "class": "BiosVfQuietBoot",
                    "properties": {
                        "vp_quiet_boot": "disabled"
                    }
                },{
                    "module": "ucsmsdk.mometa.bios.BiosVfResumeOnACPowerLoss",
                    "class": "BiosVfResumeOnACPowerLoss",
                    "properties": {
                        "vp_resume_on_ac_power_loss": "stay-off"
                    }
                },{
                    "module": "ucsmsdk.mometa.bios.BiosVfConsoleRedirection",
                    "class": "BiosVfConsoleRedirection",
                    "properties": {
                        "vp_baud_rate": "9600",
                        "vp_console_redirection": "com-0",
                        "vp_terminal_type": "pc-ansi"
                    }
                }]
      }
      state: "{{ ucs_state }}"