---

#
# Author: John McDonough (jomcdono@cisco.com)
#         Cisco Systems, Inc.
#
###########################################################
#           Playbook to manage UCS VLANs                  #
###########################################################

- name: UCS VLAN Management
  hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Test that we have a UCS hostname, username, and password
    fail:
      msg: 'Please define the variables: ucs_hostname, ucs_username and ucs_password.'
    when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
    vars:
      login_info: &login_info
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"

  - debug:
      msg: ucs_state is {{ ucs_state }}

  - name: Configure VLAN
    ucs_vlans:
      <<: *login_info
      name: "{{ item.name }}"
      id: "{{ item.id }}"
      native: "{{ item.native }}"
      state: "{{ ucs_state }}"
    loop:
      "{{ vlans }}"
    when: ucs_state == 'present'


  - name: Remove VLAN
    ucs_vlans:
      <<: *login_info
      name: "{{ item.name }}"
      id: "{{ item.id }}"
      native: "{{ item.native }}"
      state: "{{ ucs_state }}"
    loop:
      "{{ vlans }}"
    when: ucs_state == 'absent'
