---

#
# Author: John McDonough (jomcdono@cisco.com)
#         Cisco Systems, Inc.
#
###########################################################
#           Playbook to manage nxos switches              #
###########################################################

  - name: Configure VLANs
    hosts: nxos
    connection: local
    gather_facts: no

    tasks:
    - debug:
        msg: nxos_state is {{ nxos_state }}

    - name: "Configure VLAN"
      nxos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }} "
        state: "{{ nxos_state }}"
      when: nxos_state == 'present'
      with_items: "{{ vlans }}"

    - name: "Remove VLAN"
      nxos_vlan:
        vlan_range: "{{ vlan_range }}"
        state: "{{ nxos_state }}"
      when: nxos_state == 'absent'
