---

#
# Author: John McDonough (jomcdono@cisco.com)
#         Cisco Systems, Inc.
#
###########################################################
#           Playbook to configure nxos switches           #
###########################################################

  - name: Configure VLANs
    hosts: nxos_switches
    connection: local
    gather_facts: no

    tasks:
    - name: "Configure VLANs"
      nxos_vlan:
        host: "{{ nxos_hostname }}"
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }} "
        state: "{{ nxos_state }}"
        transport: nxapi
      with_items: "{{ vlans }}"