---
###########################################################
#           Playbook to configure nxos switches           #
###########################################################
  - name: Retrieve facts from nxos switches
    hosts: nxos-switches
    connection: local

    tasks:
    - name: "Configure VLANs"
      with_items: "{{ vlans }}"
      nxos_vlan:
        host: "{{ inventory_hostname }}"
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }} "
        state: present
        transport: nxapi