---

#
# Author: John McDonough (jomcdono@cisco.com)
#         Cisco Systems, Inc.
#
#############################
#  Playbook for NXOS VLANS  #
#############################

- name: NXOS VLAN Management
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - debug:
      msg: nxos_state is {{ nxos_state }}

  - name: Include Tenant vars
    include_vars:
      file: "{{ app_name }}.yml"

  - name: "Configure VLAN"
    nxos_vlan:
      vlan_id: "{{ item.vlan_id }}"
      name: "{{ item.name }} "
      state: "{{ nxos_state }}"
    when: nxos_state == 'present'
    with_items: "{{ vlans }}"

  - name: "Remove VLAN"
    nxos_vlan:
      vlan_range: "{{ vlan_range }}"
      state: "{{ nxos_state }}"
    when: nxos_state == 'absent'
