---
# shared policies, use localhost so these tasks only run once
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
    resource_state: absent

  tasks:
  - name: Delete Boot Policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /boot/PrecisionPolicies
      query_params:
        $filter: "Name eq 'vmedia-hdd2'"
      state: absent
